export const service = [
  {
    id: 1,
    name: "Free Fire(UID)",
    img: "https://images.pexels.com/photos/78783/submachine-gun-rifle-automatic-weapon-weapon-78783.jpeg?auto=compress&cs=tinysrgb&w=600",
    items: [
      { id: "uid1", name: "115", price: 80, icon: "" },
      { id: "uid2", name: "115", price: 100, icon: "" },
      { id: "uid3", name: "115", price: 200, icon: "" },
      { id: "uid4", name: "115", price: 300, icon: "" },
      { id: "uid5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 2,
    name: "Uid Membersh",
    img: "",
    items: [
      { id: "Uid1", name: "115", price: 80, icon: "" },
      { id: "Uid2", name: "115", price: 100, icon: "" },
      { id: "Uid3", name: "115", price: 200, icon: "" },
      { id: "Uid4", name: "115", price: 300, icon: "" },
      { id: "Uid5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 3,
    name: "Level Up pass",
    img: "",
    items: [
      { id: "levelUp1", name: "115", price: 80, icon: "" },
      { id: "levelUp2", name: "115", price: 100, icon: "" },
      { id: "levelUp3", name: "115", price: 200, icon: "" },
      { id: "levelUp4", name: "115", price: 300, icon: "" },
      { id: "levelUp5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 4,
    name: "Garena MY SHells",
    img: "",
    items: [
      { id: "garena1", name: "115", price: 80, icon: "" },
      { id: "garena2", name: "115", price: 100, icon: "" },
      { id: "garena3", name: "115", price: 200, icon: "" },
      { id: "garena4", name: "115", price: 300, icon: "" },
      { id: "garena5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 5,
    name: "IN Game Top Up",
    img: "",
    items: [
      { id: "ingame1", name: "115", price: 80, icon: "" },
      { id: "ingame2", name: "115", price: 100, icon: "" },
      { id: "ingame3", name: "115", price: 200, icon: "" },
      { id: "ingame4", name: "115", price: 300, icon: "" },
      { id: "ingame5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 6,
    name: "Plus Point",
    img: "",
    items: [
      { id: "plus1", name: "115", price: 80, icon: "" },
      { id: "plus2", name: "115", price: 100, icon: "" },
      { id: "plus3", name: "115", price: 200, icon: "" },
      { id: "plus4", name: "115", price: 300, icon: "" },
      { id: "plus5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 7,
    name: "Big Offer",
    img: "",
    items: [
      { id: "mship1", name: "115", price: 80, icon: "" },
      { id: "mship2", name: "115", price: 100, icon: "" },
      { id: "mship3", name: "115", price: 200, icon: "" },
      { id: "mship4", name: "115", price: 300, icon: "" },
      { id: "mship5", name: "115", price: 1800, icon: "" },
    ],
  },
  {
    id: 7,
    name: "Big Offer",
    img: "",
    items: [
      { id: "bigoff1", name: "115", price: 80, icon: "" },
      { id: "bigoff2", name: "115", price: 100, icon: "" },
      { id: "bigoff3", name: "115", price: 200, icon: "" },
      { id: "bigoff4", name: "115", price: 300, icon: "" },
      { id: "bigoff5", name: "115", price: 1800, icon: "" },
    ],
  },
];
